### ISSUE TITLE
Small error in FM Mouse Example save/load

### ISSUE THREAD

**Issue by tmhglnd** [alexdrymonitis/neuralnet#4]
Hi! 

I was trying the `03_mouse_input.pd` example, and I found a small error in the `[pd save_and_load]` subpatcher. It didn't store the files for me because the send objects have the name `mnist_example`, changing this to `mouse_input_example` fixed it. 

Best!

**Comment by alexdrymonitis** [comment]
Thanks for the heads up! It is now fixed.
